HTML markup
stzabiyaka/icecream-team-project pull request #6
Opened 2022-01-29 18:22 UTC by VitenFra

Создал HTML разметку и залил 3 иконки в хорошем качестве

2022-01-29 19:43 UTC, stzabiyaka requested changes

2022-01-29 19:43 UTC, stzabiyaka commented on src/partials/advantages.html
> +<section id="advantages" class="advantages">
Здесь нужно навесить ещё один класс section через пробел после advantages

2022-01-29 19:43 UTC, stzabiyaka commented on src/partials/advantages.html
> +  <h2 class="advantages__title">Advantages</h2>
здесь нужно заменить класс "advantages__title" на "section__title--hidden", чтобы скрыть заголовок со страницы

2022-01-29 21:05 UTC, VitenFra commented on src/partials/advantages.html
> +<section id="advantages" class="advantages">
добавил

2022-01-29 21:05 UTC, VitenFra commented on src/partials/advantages.html
> +  <h2 class="advantages__title">Advantages</h2>
заменил

2022-01-30 08:43 UTC, stzabiyaka approved these changes

2022-01-30 08:43 UTC, merged