mobile-version
stzabiyaka/icecream-team-project pull request #8
Opened 2022-01-29 20:09 UTC by Julanna11

2022-01-29 21:17 UTC, stzabiyaka requested changes
В целом всё отлично. Нужно исправить замечания и закоммитить, а на следующей итерации  сверстать два блока для модальной карты - просто два квадратных дива с размерами примерно на треть ширины экрана для всех точек перелома

2022-01-29 21:17 UTC, stzabiyaka commented on src/partials/contacts.html
> +    <h2 class="section__title section__title--hidden">Contacts</h2>
Здесь нужно оставить только класс section__title--hidden

2022-01-29 21:17 UTC, stzabiyaka commented on src/partials/contacts.html
> +        <svg class="button__icon">
здесь нужно добавить через пробел класс button__icon-aapend для позиционирования иконки относительно текста кноки

2022-01-29 21:17 UTC, stzabiyaka commented on src/sass/partials/_contacts.scss
> +    color: #FFFFFF;
цвет лучше задавать переменной color: getColor('background-primary')

2022-01-29 21:17 UTC, stzabiyaka commented on src/sass/partials/_contacts.scss
> +color: #FFA5BA;
этот цвет у нас подвязан к переменной 'text-label'

2022-01-29 21:17 UTC, stzabiyaka commented on src/sass/partials/_contacts.scss
> +color: #907E82;
а это цвет в переменной 'text-primary'

2022-01-30 14:34 UTC, Julanna11 commented on src/partials/contacts.html
> +        <svg class="button__icon">
done

2022-01-30 14:34 UTC, Julanna11 commented on src/sass/partials/_contacts.scss
> +    color: #FFFFFF;
done

2022-01-30 14:36 UTC, stzabiyaka approved these changes

2022-01-30 14:36 UTC, merged